#!/usr/bin/env bash
# This script installs and configures nginx web server

apt -y update
apt -y install nginx

ufw allow 'Nginx HTTP'
service nginx start
echo "Hello World!" > /var/www/html/index.html
nginx -s reload
