#!/usr/bin/env bash
# This script installs and configures nginx web server

apt-get -y update
apt-get -y install nginx

html="/var/www/html/index.html"
echo "Hello World!" > "$html"

config="/etc/nginx/sites-available/default"
text="\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}\n}"

sed -i -r "s/^}$/$text/" "$config"

service nginx restart
