#!/usr/bin/env bash
# Transfers file to a user home directory in a remote server using ssh

# variables
path_to_file=$1
remote_ip=$2
username=$3
path_to_private_key=$4

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ -n "$4" ]; then
		scp -o StrictHostKeyChecking=no -i "$path_to_private_key" "$path_to_file" "$username"@"$remote_ip":~/
	else
		scp -o StrictHostKeyChecking=no "$path_to_file" "$username"@"$remote_ip":~/
	fi

fi
