#!/usr/bin/env bash
# This script installs and configures nginx web server

apt -y update
apt -y install nginx

# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
rm -rf /etc/nginx/sites-enabled/
ln -s /etc/nginx/sites-available/ /etc/nginx/sites-enabled
service nginx start
