#!/usr/bin/env bash
# sets up ufw firewall and blocks all incoming traffic
# Allowing only port 22 ssh, 80 http and 433 https

ufw default allow outgoing
ufw default deny incoming

ufw allow OpenSSH
# ufw allow ssh. based on /etc/service file the port is located
ufw allow 22  # ssh for added verification
ufw allow 80  # HTTP
ufw allow 443 # HTTPS

ufw enable
