#!/usr/bin/env bash

# Connects to a remote server using ssh
# remote_host=command line para,m
# path="$HOME/.ssh/school"
# username="ubuntu"
ip=$1

# ssh -i "$path" -t "$username"@"$remote_host"
ssh -i ~/.ssh/school ubuntu@$ip
